name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - TradeTracker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          php-version: '8.2' 
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Create .env from secret
        run: echo "$ENV_CONTENT" > .env
        env:
          ENV_CONTENT: ${{ secrets.ENV_CONTENT }}

      - name: Upload to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST_NAME}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./        # upload everything from repo root
          server-dir: /htdocs/ # folder yaInfinityFree
          exclude: |
            .git*
            .github*
            node_modules
            tests
